# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db29097cbe5b2d9f65636776ada06cc66fd24281c29f362154347a4d5e5d144888b331d6bf9903679c8762b2e8e0c145afeb0194d7cd46aef5e5e4f55bff9ccc

test:
  secret_key_base: 503ef5503c7e70d06bd2a0f327433057aefb05c8c5a7cb2673592cf1e0727648a6d0cdde4a7008c98c4e383340770f668987ae2d0fd61b41082f62fcfda31764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
